---
- name: Python-Projekt vorbereiten und ausführen
  hosts: appserver
  become: yes

  vars:
    project_dir: /opt/myapp
    repo_url: "https://github.com/dein-user/dein-repo.git"

  tasks:
    - name: Git installieren
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Python3 + pip installieren
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Projektverzeichnis klonen
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        version: main

    - name: Abhängigkeiten installieren
      pip:
        requirements: "{{ project_dir }}/requirements.txt"

    - name: App starten (z.B. Flask)
      shell: |
        nohup python3 {{ project_dir }}/app.py &
      args:
        chdir: "{{ project_dir }}"
        creates: "/tmp/app_started"
