---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel

  tasks:
    - name: Ensure net-tools is installed (for netstat)
      ansible.builtin.dnf:
        name: net-tools
        state: present