base_dir: C:\home\ma_simon\ansible_bench
output_dir: output
dataset_dir: dataset
config_dir: config
logs_dir: logs
testresults_dir: testresults #not needed yet
postprocessing_reports_dir: postprocessing_reports #not needed yet
temp_exec_dir: temp #not needed yet